### ISSUE TITLE
Missing properties in typescript types

### ISSUE THREAD

**Issue by gmencz** [joonhocho/graphql-scalar#4]
The `name` and `description` properties are not defined in the types, therefor when setting the `name` (which is mandatory), you have to tell typescript to ignore it otherwise we get the unknown property error.

![Screenshot_9](https://user-images.githubusercontent.com/43379549/84956230-070f2600-b0f9-11ea-8004-f736e1cfc681.png)

**Comment by homoky** [comment]
Yes I just found out the same thing.

**Comment by ardeois** [comment]
This is because you need to install `tsdef` package

I've fixed it in this PR https://github.com/joonhocho/graphql-scalar/pull/7

**Comment by joonhocho** [comment]
added `tsdef` as dependency as requested.
